services:
  spring-boot:
    build: .
    container_name: shipment-service
    ports:
      - "8080:8080"
    networks:
      - elk

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    ports:
      - "4040:4040"
    env_file:
      - application.yml
    command: http spring-boot:8080
    networks:
      - elk
    depends_on:
      - spring-boot

networks:
  elk:
    external: true
    name: docker-elk_elk