spring:
  application:
    name: batchie
  data:
    mongodb:
      host: localhost
      port: 27017
      database: aster
      authentication-database: admin
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    org.springframework: INFO
  file:
    name: logs/application.log
